// eslint-disable-next-line import/prefer-default-export
export const CUSTOMER_STATUS_TYPES = {
  REJECTED: 'REJECTED',
  IDLE: 'IDLE',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  WHITELISTED: 'WHITELISTED',
  CONTRACTED: 'CONTRACTED',
  KYC_LVL_CHANGE: 'KYC_LVL_CHANGE',
  REOPEN: 'REOPEN',
}

export const CUSTOMER_TYPES = {
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY',
}

export const SOURCE_OF_FUNDS = {
  SAVINGS: 'SAVINGS',
  SALE_OF_INVESTMENTS: 'SALE_OF_INVESTMENTS',
  SALE_OF_PROPERTY: 'SALE_OF_PROPERTY',
  LOAN: 'LOAN',
  INHERITANCE: 'INHERITANCE',
  MATURITY_OR_SURRENDER_OF_LIFE_ASSURANCE_POLICY: 'MATURITY_OR_SURRENDER_OF_LIFE_ASSURANCE_POLICY',
  INSURANCE_CLAIMS: 'INSURANCE_CLAIMS',
  DIVIDENDS_OR_PROFITS_FROM_COMPANY: 'DIVIDENDS_OR_PROFITS_FROM_COMPANY',
  DIVORCE: 'DIVORCE',
  OTHER_COURT_AWARD: 'OTHER_COURT_AWARD',
  LOTTERY: 'LOTTERY',
  GAMBLING_WIN: 'GAMBLING_WIN',
  GIFT: 'GIFT',
  OTHER: 'OTHER',
}
