// eslint-disable-next-line import/prefer-default-export
export const TRANSACTIONS_STATUS_TYPES = {
  REJECTED: 'REJECTED',
  IDLE: 'IDLE',
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  APPROVED: 'APPROVED',
  CONTRACTED: 'CONTRACTED',
}

export const TRANSACTIONS_TYPES = {
  PURCHASE: 'PURCHASE',
}

export const PAYMENT_TYPES = {
  BANK_TRANSFER: 'BANK_TRANSFER',
  PAYPAL: 'PAYPAL',
  CRYPTO: 'CRYPTO',
  WALLET: 'WALLET',
  VOLT: 'VOLT',
}
