import React from 'react'

import '../styles/legacy/style.scss'
import AppBar from '../components/AppBar'
import Footer from '../components/Footer'

const Terms = () => (
  <div className="page-user">
    <AppBar />
    <div className="page-content">
      <div className="container">
        <div className="card content-area">
          <div className="card-innr">
            <div className="card-head">
              <h4 className="card-title card-title-lg">Terms</h4>
            </div>

COOKIE POLICY


Cookie Policy

As is common on many other corporate websites, we also use so-called "cookies" and other technologies to gain better insight into which areas of our site are particularly popular, how our visitors move around the site, and how much time you spend in different areas. In addition, we use cookies and other technologies to ensure that our online advertising is effective and that customers are indeed aware of our products and services. We use cookies and other technologies to analyze the traffic on our website so that we can further improve their design and functionality, and to investigate the efficiency of communication with our customers. We also use cookies to better tailor the site to your needs and provide you with more navigation convenience every time you visit. Like most websites, we also automatically collect certain information and store it in log files. This information includes Internet Protocol (IP) addresses, browser type, Internet Service Provider (ISP), referral / end pages, operating system, date / time stamps, and clickstream data. In some of our email messages, we also use so-called "click-through URLs" that are linked to content on our website. If you click in such a URL address, you pass our web server before you reach the actual target web page. We track this "click-through" data to determine the interest in specific topics and to measure the effectiveness of communicating with our customers. If you want to avoid capturing such data, simply do not click on any text or graphic links in emails. In addition, we use so-called "pixel tags" (tiny image files) that provide information about which parts of our site customers have visited, this measure how effective customer searches have been on our site. In addition, pixel tags can be used to send email messages in a customer-readable format. It also allows us to check if emails have been opened to ensure that only those messages are sent that really interest our customers.


USE OF EXTERNAL SERVICES (INCL. TRACKING SERVICES)

Within the website third-party content, such as videos from YouTube and maps from Google Maps are included. For the use of such content, the transmission of the IP address of the user to the respective third party is technically required. Without the IP address, the third-party providers would not be able to send the content embedded in the website to the browser of the respective user. We have no control over whether a third party provider stores or otherwise uses the IP address for statistical purposes, for example. Third party providers are independent owners of cookies, so their policies apply.

Third party providers can be:
Google Analytics Universal Tracking
Google My Business, Google+, Google Maps, Youtube
Google Adwords Remarketing
Google Adwords Conversion
Facebook and Facebook conversion
various social media services
Newsletter registration and newsletter service
Statistics and analysis services various third-party contractors
and accounting and valuation services


USE OF VARIOUS OTHER COOKIE SERVICES

What is a cookie? A cookie is a small text file that is stored on your device when you visit a website and helps to identify your device. Cookies are used to store information when you visit various pages on a website or return to a website. They contain no personal information and can not run programs that could trigger a virus. Manage and delete cookies: If you want to block or delete cookies, you can make these changes in the browser settings. For the administration of cookies, most browsers allow you to accept or reject all cookies or to accept only certain types of cookies. You can also set it to ask you every time a website wants to save a cookie. The procedures for managing and deleting cookies vary, depending on which browser you use. To find out how to do this in a specific browser, you can use the browser's built-in help function or alternatively visit www.aboutcookies.org. Here it is explained step by step how to manage and delete cookies in most popular browsers.


USING GOOGLE ANALYTICS

This website uses Google Analytics, a web analytics service provided by Google Inc. ("Google"). Google Analytics uses so-called "cookies", text files that are stored on your computer and that allow an analysis of the use of the website by them. The information generated by the cookie about your use of this website is usually transmitted to a Google server in the USA and stored there. By activating IP anonymization on this website, however, your IP address will be shortened by Google beforehand within member states of the European Union or in other contracting states of the Agreement on the European Economic Area. Only in exceptional cases will the full IP address be sent to a Google server in the USA and shortened there. On behalf of the operator of this website, Google will use this information to evaluate your use of the website, to compile reports on website activity and to provide other services related to website activity and internet usage to the website operator. The IP address provided by Google Analytics as part of Google Analytics will not be merged with other Google data. You can prevent the storage of cookies by setting your browser software accordingly. Please note that in this case you may not be able to use all features of this website. The collection of data you can prevent your use of this website (including your IP address) and the processing of this data by Google by downloading and installing the browser plug-in available at tools.google.com. You can still prevent Google Analytics from collecting it by clicking on the following. An opt-out cookie is set, which prevents the future collection of your data when visiting this website: Disable Google Analytics. For more information about Google Analytics terms of service and privacy, visit: Google Analytics and support.google.com. This website uses Google Analytics via IP-Masking to ensure an anonymous collection of IP addresses. Please note that we continue to use Google Analytics to analyze data from AdWords and the Double-Click cookie for statistical purposes. If you do not want this, you can disable it through the Ads Preferences Manager at adssettings.google.com.


USING ADWORDS REMARKETING

This website uses cookies for the purpose of using a remarketing campaign to engage visitors with online advertising at a later date on the Google Network. To run remarketing ads, third parties such as Google use cookies based on a visit to this site. As a user, you have the option to disable Google's use of cookies by visiting the Google Disable page at adssettings.google.com.

          </div>
        </div>
      </div>
    </div>

    <Footer />
  </div>
)

export default Terms
